' <auto-generated> by Tools\FrmConverter from ..\Lib\Form\frmLogo.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes (, handled by hand in the form's code / designer):
'   - VB.Shape Shape1: Shape=3 (oval/rounded) drawn as a rectangle Label -- paint it if the shape matters
'   - VB.Shape Shape1: BorderColor=&H00E0E0E0& -- a Label border is always the system colour
Partial Class frmLogo

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

End Class
