' <auto-generated> by Tools\FrmConverter from Lib\Form\frmSaveChangedPhoto.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes: none.
Partial Class frmSaveChangedPhoto

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub
    Private _rbExecute As Aqua.RadioButton()
    ''' <summary>VB6 control array rbExecute(0..3); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property rbExecute As Aqua.RadioButton()
        Get
            If _rbExecute Is Nothing Then _rbExecute = New Aqua.RadioButton() {Me.rbExecute_0, Me.rbExecute_1, Me.rbExecute_2, Me.rbExecute_3}
            Return _rbExecute
        End Get
    End Property

End Class
