' <auto-generated> by Tools\FrmConverter from Lib\Form\frmViewerLarge.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes (resolved): mpViewerVideo is an Aqua.MediaViewerControl driven from code (Play/Pause/Stop);
' shpZero (VB6 oval) is a 3x3 Label marking the sliders' zero point.
Partial Class frmViewerLarge

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

End Class
