' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmAddition.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes: none.
Partial Class frmAddition

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _rbMode As Aqua.RadioButton()
    ''' <summary>VB6 control array rbMode(0..1); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property rbMode As Aqua.RadioButton()
        Get
            If _rbMode Is Nothing Then _rbMode = New Aqua.RadioButton() {Me.rbMode_0, Me.rbMode_1}
            Return _rbMode
        End Get
    End Property

End Class
