' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmDateTime.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes: none.
Partial Class frmDateTime

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _chkSaveMode As Aqua.CheckBox()
    ''' <summary>VB6 control array chkSaveMode(0..1); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property chkSaveMode As Aqua.CheckBox()
        Get
            If _chkSaveMode Is Nothing Then _chkSaveMode = New Aqua.CheckBox() {Me.chkSaveMode_0, Me.chkSaveMode_1}
            Return _chkSaveMode
        End Get
    End Property

    Private _txtDD As Aqua.TextBox()
    ''' <summary>VB6 control array txtDD(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtDD As Aqua.TextBox()
        Get
            If _txtDD Is Nothing Then _txtDD = New Aqua.TextBox() {Me.txtDD_0, Me.txtDD_1, Me.txtDD_2}
            Return _txtDD
        End Get
    End Property

    Private _txtHH As Aqua.TextBox()
    ''' <summary>VB6 control array txtHH(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtHH As Aqua.TextBox()
        Get
            If _txtHH Is Nothing Then _txtHH = New Aqua.TextBox() {Me.txtHH_0, Me.txtHH_1, Me.txtHH_2}
            Return _txtHH
        End Get
    End Property

    Private _txtMM As Aqua.TextBox()
    ''' <summary>VB6 control array txtMM(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtMM As Aqua.TextBox()
        Get
            If _txtMM Is Nothing Then _txtMM = New Aqua.TextBox() {Me.txtMM_0, Me.txtMM_1, Me.txtMM_2}
            Return _txtMM
        End Get
    End Property

    Private _txtNN As Aqua.TextBox()
    ''' <summary>VB6 control array txtNN(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtNN As Aqua.TextBox()
        Get
            If _txtNN Is Nothing Then _txtNN = New Aqua.TextBox() {Me.txtNN_0, Me.txtNN_1, Me.txtNN_2}
            Return _txtNN
        End Get
    End Property

    Private _txtSS As Aqua.TextBox()
    ''' <summary>VB6 control array txtSS(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtSS As Aqua.TextBox()
        Get
            If _txtSS Is Nothing Then _txtSS = New Aqua.TextBox() {Me.txtSS_0, Me.txtSS_1, Me.txtSS_2}
            Return _txtSS
        End Get
    End Property

    Private _txtYYYY As Aqua.TextBox()
    ''' <summary>VB6 control array txtYYYY(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtYYYY As Aqua.TextBox()
        Get
            If _txtYYYY Is Nothing Then _txtYYYY = New Aqua.TextBox() {Me.txtYYYY_0, Me.txtYYYY_1, Me.txtYYYY_2}
            Return _txtYYYY
        End Get
    End Property

End Class
