' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmMain.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes (, handled by hand in the form's code / designer):
'   - Aqua.Month Month1: SelIndex = -1 -- Month has no SelIndex
'   - Aqua.Calendar Calendar1: WeekFont = New System.Drawing.Font("新細明體", 15.75!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(136, Byte)) -- Calendar has no WeekFont
'   - Aqua.Calendar Calendar1: DayFont = New System.Drawing.Font("Times New Roman", 15.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte)) -- Calendar has no DayFont
'   - Aqua.iTextBox iTextBox1: AutoComplete = 1 -- ITextBox has no AutoComplete
Partial Class frmMain_1280x1024

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _imgButton As Aqua.PngButton()
    ''' <summary>VB6 control array imgButton(0..7); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property imgButton As Aqua.PngButton()
        Get
            If _imgButton Is Nothing Then _imgButton = New Aqua.PngButton() {Me.imgButton_0, Me.imgButton_1, Me.imgButton_2, Me.imgButton_3, Me.imgButton_4, Me.imgButton_5, Me.imgButton_6, Me.imgButton_7}
            Return _imgButton
        End Get
    End Property

    Private _imgToolBox As Aqua.PngButton()
    ''' <summary>VB6 control array imgToolBox(0..13), plus 14 同步備份 (new in the .NET version).</summary>
    Friend ReadOnly Property imgToolBox As Aqua.PngButton()
        Get
            If _imgToolBox Is Nothing Then _imgToolBox = New Aqua.PngButton() {Me.imgToolBox_0, Me.imgToolBox_1, Me.imgToolBox_2, Me.imgToolBox_3, Me.imgToolBox_4, Me.imgToolBox_5, Me.imgToolBox_6, Me.imgToolBox_7, Me.imgToolBox_8, Me.imgToolBox_9, Me.imgToolBox_10, Me.imgToolBox_11, Me.imgToolBox_12, Me.imgToolBox_13, Me.imgToolBox_14}
            Return _imgToolBox
        End Get
    End Property

    Private _lblToolBox As System.Windows.Forms.Label()
    ''' <summary>VB6 control array lblToolBox(0..13), plus 14 同步備份 (new in the .NET version).</summary>
    Friend ReadOnly Property lblToolBox As System.Windows.Forms.Label()
        Get
            If _lblToolBox Is Nothing Then _lblToolBox = New System.Windows.Forms.Label() {Me.lblToolBox_0, Me.lblToolBox_1, Me.lblToolBox_2, Me.lblToolBox_3, Me.lblToolBox_4, Me.lblToolBox_5, Me.lblToolBox_6, Me.lblToolBox_7, Me.lblToolBox_8, Me.lblToolBox_9, Me.lblToolBox_10, Me.lblToolBox_11, Me.lblToolBox_12, Me.lblToolBox_13, Me.lblToolBox_14}
            Return _lblToolBox
        End Get
    End Property

    Private _Line2 As System.Windows.Forms.Label()
    ''' <summary>VB6 control array Line2(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property Line2 As System.Windows.Forms.Label()
        Get
            If _Line2 Is Nothing Then _Line2 = New System.Windows.Forms.Label() {Me.Line2_0, Me.Line2_1, Me.Line2_2}
            Return _Line2
        End Get
    End Property

End Class
