' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmPhotoIndex.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes (, handled by hand in the form's code / designer):
'   - MSComDlg.CommonDialog CommonDialog1: MSComDlg.CommonDialog has no control -- use OpenFileDialog / SaveFileDialog / PrintDialog / ColorDialog in code
Partial Class frmPhotoIndex

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _chkPrintNote As Aqua.CheckBox()
    ''' <summary>VB6 control array chkPrintNote(0..1); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property chkPrintNote As Aqua.CheckBox()
        Get
            If _chkPrintNote Is Nothing Then _chkPrintNote = New Aqua.CheckBox() {Me.chkPrintNote_0, Me.chkPrintNote_1}
            Return _chkPrintNote
        End Get
    End Property

    Private _picCanvas As System.Windows.Forms.PictureBox()
    ''' <summary>VB6 control array picCanvas(0..0); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property picCanvas As System.Windows.Forms.PictureBox()
        Get
            If _picCanvas Is Nothing Then _picCanvas = New System.Windows.Forms.PictureBox() {Me.picCanvas_0}
            Return _picCanvas
        End Get
    End Property

End Class
