' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmPrintPages.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes: none.
Partial Class frmPrintPages

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub
    Private _rdPages As Aqua.RadioButton()
    ''' <summary>VB6 control array rdPages(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property rdPages As Aqua.RadioButton()
        Get
            If _rdPages Is Nothing Then _rdPages = New Aqua.RadioButton() {Me.rdPages_0, Me.rdPages_1, Me.rdPages_2}
            Return _rdPages
        End Get
    End Property

End Class
