' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmPhotoInfoBatch_2.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' The VB6 form used vbAccelerator / TechnoSoft ActiveX controls the converter could only leave as empty
' placeholder panels; the designer now rebuilds that screen with WinForms / Aqua controls:
'   vbalListViewCtl lvwMain + vbalImageList ilsIcons -> ListView (LargeIcon) + ImageList 120x96
'   vbalExplorerBarCtl barSearch                    -> scrolling Panel with the four bars as sections
'   vbalMultiSel cbo* (keyword multi-select combo)  -> "▼" Button + ContextMenuStrip mnuKeyWords (check items)
'   TechnoComCtls SkinButton but*                   -> Aqua.ThinButton
Partial Class frmPhotoInfoBatch_2

    Public Sub New()
        InitializeComponent()
    End Sub

End Class
