' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmPrint.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes (, handled by hand in the form's code / designer):
'   - MSComDlg.CommonDialog CommonDialog1: MSComDlg.CommonDialog has no control -- use OpenFileDialog / SaveFileDialog / PrintDialog / ColorDialog in code
Partial Class frmPrint

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _picPicture As System.Windows.Forms.PictureBox()
    ''' <summary>VB6 control array picPicture(0..0); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property picPicture As System.Windows.Forms.PictureBox()
        Get
            If _picPicture Is Nothing Then _picPicture = New System.Windows.Forms.PictureBox() {Me.picPicture_0}
            Return _picPicture
        End Get
    End Property

    Private _rdPrintMode As Aqua.RadioButton()
    ''' <summary>VB6 control array rdPrintMode(0..1); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property rdPrintMode As Aqua.RadioButton()
        Get
            If _rdPrintMode Is Nothing Then _rdPrintMode = New Aqua.RadioButton() {Me.rdPrintMode_0, Me.rdPrintMode_1}
            Return _rdPrintMode
        End Get
    End Property

End Class
