' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmPhotoInfo.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes (, handled by hand in the form's code / designer):
'   - Aqua.TextBox txtCharacter: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.TextBox txtTitle: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.TextBox txtKeyWord: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.TextBox txtRemark: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.TextBox txtSpot: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.MaskEdit meDate: MaxLength = 10 -- MaskEdit has no MaxLength
'   - Aqua.MaskEdit meDate: Format = "0000/00/00" -- MaskEdit has no Format
'   - Aqua.MaskEdit meTime: MaxLength = 8 -- MaskEdit has no MaxLength
'   - Aqua.MaskEdit meTime: Format = "00:00:00" -- MaskEdit has no Format
Partial Class frmPhotoInfo

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _imgKeyWords As Aqua.PngButton()
    ''' <summary>VB6 control array imgKeyWords(0..4); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property imgKeyWords As Aqua.PngButton()
        Get
            If _imgKeyWords Is Nothing Then _imgKeyWords = New Aqua.PngButton() {Me.imgKeyWords_0, Me.imgKeyWords_1, Me.imgKeyWords_2, Me.imgKeyWords_3, Me.imgKeyWords_4}
            Return _imgKeyWords
        End Get
    End Property

End Class
