' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmPaperSetup.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes: none.
Partial Class frmPaperSetup

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _txtEdge As Aqua.TextBox()
    ''' <summary>VB6 control array txtEdge(0..3); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtEdge As Aqua.TextBox()
        Get
            If _txtEdge Is Nothing Then _txtEdge = New Aqua.TextBox() {Me.txtEdge_0, Me.txtEdge_1, Me.txtEdge_2, Me.txtEdge_3}
            Return _txtEdge
        End Get
    End Property

    Private _txtKeep As Aqua.TextBox()
    ''' <summary>VB6 control array txtKeep(0..1); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtKeep As Aqua.TextBox()
        Get
            If _txtKeep Is Nothing Then _txtKeep = New Aqua.TextBox() {Me.txtKeep_0, Me.txtKeep_1}
            Return _txtKeep
        End Get
    End Property

End Class
