' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmSetup.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' VB6's PageHead1 + PageSheet1(0..3) are the TabControl tabSetup and its pages pageGeneral, pageAlbums,
' pageAppearance, pagePlugins (renamed from the VB6 names; the PageSheet1() array was never used).
Partial Class frmSetup

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _imgAlbums As Aqua.IconBox()
    ''' <summary>VB6 control array imgAlbums(0..3); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property imgAlbums As Aqua.IconBox()
        Get
            If _imgAlbums Is Nothing Then _imgAlbums = New Aqua.IconBox() {Me.imgAlbums_0, Me.imgAlbums_1, Me.imgAlbums_2, Me.imgAlbums_3}
            Return _imgAlbums
        End Get
    End Property

    Private _imgApp As System.Windows.Forms.PictureBox()
    ''' <summary>VB6 control array imgApp(0..5); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property imgApp As System.Windows.Forms.PictureBox()
        Get
            If _imgApp Is Nothing Then _imgApp = New System.Windows.Forms.PictureBox() {Me.imgApp_0, Me.imgApp_1, Me.imgApp_2, Me.imgApp_3, Me.imgApp_4, Me.imgApp_5}
            Return _imgApp
        End Get
    End Property

    Private _imgAttached As System.Windows.Forms.PictureBox()
    ''' <summary>VB6 control array imgAttached(0..3); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property imgAttached As System.Windows.Forms.PictureBox()
        Get
            If _imgAttached Is Nothing Then _imgAttached = New System.Windows.Forms.PictureBox() {Me.imgAttached_0, Me.imgAttached_1, Me.imgAttached_2, Me.imgAttached_3}
            Return _imgAttached
        End Get
    End Property

    Private _imgSound As System.Windows.Forms.PictureBox()
    ''' <summary>VB6 control array imgSound(0..4); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property imgSound As System.Windows.Forms.PictureBox()
        Get
            If _imgSound Is Nothing Then _imgSound = New System.Windows.Forms.PictureBox() {Me.imgSound_0, Me.imgSound_1, Me.imgSound_2, Me.imgSound_3, Me.imgSound_4}
            Return _imgSound
        End Get
    End Property

    Private _rbStyle As Aqua.RadioButton()
    ''' <summary>VB6 control array rbStyle(0..1); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property rbStyle As Aqua.RadioButton()
        Get
            If _rbStyle Is Nothing Then _rbStyle = New Aqua.RadioButton() {Me.rbStyle_0, Me.rbStyle_1}
            Return _rbStyle
        End Get
    End Property

    Private _txtApp As Aqua.TextBox()
    ''' <summary>VB6 control array txtApp(0..5); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtApp As Aqua.TextBox()
        Get
            If _txtApp Is Nothing Then _txtApp = New Aqua.TextBox() {Me.txtApp_0, Me.txtApp_1, Me.txtApp_2, Me.txtApp_3, Me.txtApp_4, Me.txtApp_5}
            Return _txtApp
        End Get
    End Property

    Private _txtAttached As Aqua.TextBox()
    ''' <summary>VB6 control array txtAttached(0..3); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtAttached As Aqua.TextBox()
        Get
            If _txtAttached Is Nothing Then _txtAttached = New Aqua.TextBox() {Me.txtAttached_0, Me.txtAttached_1, Me.txtAttached_2, Me.txtAttached_3}
            Return _txtAttached
        End Get
    End Property

    Private _txtSound As Aqua.TextBox()
    ''' <summary>VB6 control array txtSound(0..4); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property txtSound As Aqua.TextBox()
        Get
            If _txtSound Is Nothing Then _txtSound = New Aqua.TextBox() {Me.txtSound_0, Me.txtSound_1, Me.txtSound_2, Me.txtSound_3, Me.txtSound_4}
            Return _txtSound
        End Get
    End Property

End Class
