' <auto-generated> by Tools\FrmConverter from iPhoto\Form\frmSearch.frm.
' Listed in FrmConverter.keep: no longer regenerated -- maintained by hand like the .Designer.vb.
'
' Converter notes (, handled by hand in the form's code / designer):
'   - Aqua.TextBox txtRemark: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.TextBox txtKeyWord: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.MaskEdit meStartDate: MaxLength = 10 -- MaskEdit has no MaxLength
'   - Aqua.MaskEdit meStartDate: Format = "yyyy/mm/dd" -- MaskEdit has no Format
'   - Aqua.MaskEdit meEndDate: MaxLength = 10 -- MaskEdit has no MaxLength
'   - Aqua.MaskEdit meEndDate: Format = "yyyy/mm/dd" -- MaskEdit has no Format
'   - Aqua.TextBox txtTitle: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.TextBox txtCharacter: AutoComplete = 1 -- TextBox has no AutoComplete
'   - Aqua.TextBox txtSpot: AutoComplete = 1 -- TextBox has no AutoComplete
Partial Class frmSearch

    Public Sub New()
        InitializeComponent()
        InitializeVb6()
    End Sub

    ''' <summary>VB6 designer content the WinForms designer can't hold (list-style properties:
    ''' Buttons/ToolBar items, Grid headers, AquaMenu items, ImageList images, ListView columns).</summary>
    Private Sub InitializeVb6()
    End Sub

    Private _imgKeyWords As Aqua.PngButton()
    ''' <summary>VB6 control array imgKeyWords(0..4); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property imgKeyWords As Aqua.PngButton()
        Get
            If _imgKeyWords Is Nothing Then _imgKeyWords = New Aqua.PngButton() {Me.imgKeyWords_0, Me.imgKeyWords_1, Me.imgKeyWords_2, Me.imgKeyWords_3, Me.imgKeyWords_4}
            Return _imgKeyWords
        End Get
    End Property

    Private _rbRange As Aqua.RadioButton()
    ''' <summary>VB6 control array rbRange(0..2); indexes VB6 didn't use are Nothing.</summary>
    Friend ReadOnly Property rbRange As Aqua.RadioButton()
        Get
            If _rbRange Is Nothing Then _rbRange = New Aqua.RadioButton() {Me.rbRange_0, Me.rbRange_1, Me.rbRange_2}
            Return _rbRange
        End Get
    End Property

End Class
